FROM convention-api-build:local as build
FROM mcr.microsoft.com/dotnet/aspnet:3.1
RUN mkdir /app
WORKDIR app
COPY --from=build /src/convention-website/bin/Release/netcoreapp3.1/publish/ ./
ENTRYPOINT ["dotnet", "/app/convention-website.dll" ]
